# Playtime

We start by playing a bit with `R` and its functionalities.

In [7]:
x <- 10   # this is an assignment
print(x)  # this one way to print a variable
x         # this is another

[1] 10


[1] 10

In [12]:
z <- 1:10 # create a linspace
print(z)
z

 [1]  1  2  3  4  5  6  7  8  9 10


[1]  1  2  3  4  5  6  7  8  9 10

In [14]:
10L # explicitly returns an integer
Inf # infinity is handled

[1] 10

[1] Inf

In [21]:
x <- c(0, 2, 4, 6, 8) # create a concatenation (must be same type or castable)
x

[1] 0 2 4 6 8

In [24]:
x <- vector(mode = 'numeric', length = 10) # instantiate an all zero numeric vector
x

[1] 0 0 0 0 0 0 0 0 0 0

In [27]:
x <- 0:10
as.logical(x)   # convert to bool
as.numeric(x)   # convert to numeric
as.character(x) # convert to character

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

[1]  0  1  2  3  4  5  6  7  8  9 10

[1] "0"  "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [96]:
x <- list('a', 10, TRUE) # lists can host different types
x

[[1]]
[1] "a"

[[2]]
[1] 10

[[3]]
[1] TRUE

In [101]:
x[[1]] # single components are accessible through double squared brackets
x[[2]]
x[[3]]

[1] "a"

[1] 10

[1] TRUE

In [104]:
x[1] # single squared brackets return same class as origin
x[2]
x[3]
x[1:2]
u <- x == TRUE # create logical vector
x[u]           # access slice from logical vector

[[1]]
[1] "a"

[[1]]
[1] 10

[[1]]
[1] TRUE

[[1]]
[1] "a"

[[2]]
[1] 10

[[1]]
NULL

[[2]]
[1] 10

[[3]]
[1] TRUE

In [36]:
x <- matrix(nrow = 2, ncol = 3)
attributes(x)
dim(x)

$dim
[1] 2 3

[1] 2 3

In [45]:
x <- matrix(1:6, nrow = 2, ncol = 3) # matrices are filled column-wise
x

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [46]:
dim(x) <- c(3,2) # the dimension can be overwritten (reshape)
x

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [48]:
x <- 1:10
y <- 2:6

cbind(x,y) # create matrix through column binding
rbind(x,y) # create matrix through row binding

x  y
 [1,]  1 2
 [2,]  2 3
 [3,]  3 4
 [4,]  4 5
 [5,]  5 6
 [6,]  6 2
 [7,]  7 3
 [8,]  8 4
 [9,]  9 5
[10,] 10 6

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
x 1    2    3    4    5    6    7    8    9    10   
y 2    3    4    5    6    2    3    4    5     6

In [51]:
x <- c('yes', 'no', 'yes')
y <- factor(x) # factors are labelled versions of data
y

[1] yes no  yes
Levels: no yes

In [53]:
table(y) # group factor by levels

y
 no yes 
  1   2 

In [54]:
unclass(y) # return categorical levels

[1] 2 1 2
attr(,"levels")
[1] "no"  "yes"

In [57]:
x <- factor(c('yes', 'no', 'yes'), levels = c('yes', 'no')) # tell R that 'yes' is the first level

In [61]:
x <- c(2, 3, NaN, NA, 5)
is.na(x)  # check for missing values
is.nan(x) # check for missing numerical values

[1] FALSE FALSE  TRUE  TRUE FALSE

[1] FALSE FALSE  TRUE FALSE FALSE

In [105]:
x <- data.frame(foo = 1:4, bar = 5:8) # a data frame is a specific list where columns have all the same length
x

foo bar
1 1   5  
2 2   6  
3 3   7  
4 4   8

In [66]:
attributes(x)

$names
[1] "foo" "bar"

$class
[1] "data.frame"

$row.names
[1] 1 2 3 4

In [108]:
x$bar      # call by name
x['foo']   # call by name
x[['foo']]

[1] 5 6 7 8

foo
1 1  
2 2  
3 3  
4 4

[1] 1 2 3 4

In [115]:
x$ba                        # looks for names matching the pattern 'ba'
x[['ba']]                   # returns NULL
x[['ba', exact = FALSE]]    # does as in the first case

[1] 5 6 7 8

NULL

[1] 5 6 7 8

In [68]:
nrow(x)
ncol(x)

[1] 4

[1] 2

In [73]:
x <- c(1, 3, 4)
x
names(x) <- c('a', 'b', 'c') # add names to rows (or columns)
x

[1] 1 3 4

a b c 
1 3 4

In [83]:
x <- c(a = 1, b = 2)
x
x <- list(a = 1, b = 2)
x
x <- matrix(1:4, nrow = 2, ncol = 2)
dimnames(x) <- list(c('a', 'b'), c('aa', 'bb')) # add names to matrix
x

a b 
1 2

$a
[1] 1

$b
[1] 2

aa bb
a 1  3 
b 2  4

In [88]:
x <- data.frame(foo = 1:10, bar = 2:11) # create a dataframe
classes <- sapply(x, class)             # apply the function class to each column
classes                                 # e.g. we can then do full_table <- read.csv('table.csv', colClasses = classes) to save a bit of memory

foo       bar 
"integer" "integer"

In [92]:
dput(x) # dput gives additional info for storing data which can be reproduced (e.g. from dget(file))

structure(list(foo = 1:10, bar = 2:11), class = "data.frame", row.names = c(NA, 
-10L))


In [118]:
x <- c(2, 3, NaN, 4, NaN)
u <- is.nan(x)
x[!u]                      # remove NaNs

[1] 2 3 4

In [122]:
x <- c(1, 2, NA, 3, NA)
y <- c('a', 'b', 'c', 'd', NA)
u <- complete.cases(x,y)      # take only subset without incomplete cases

x[u]
y[u]

[1] 1 2 3

[1] "a" "b" "d"

In [125]:
x <- matrix(1:4, nrow = 2, ncol = 2); y <- matrix(5:8, nrow = 2, ncol = 2)

x * y   # element wise
x %*% y # true matrix multiplication

[,1] [,2]
[1,]  5   21  
[2,] 12   32

[,1] [,2]
[1,] 23   31  
[2,] 34   46